version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/discord-dn-bot/
    
branch_config:
    master:
        deploymentGroupName: githubdeploy
        deploymentGroupConfig:
            serviceRoleArn: arn:aws:iam::241779098843:role/CodeDeployServiceRole
        deploymentConfig:
            autoRollbackConfiguration:
                enabled: false
    '.*': ~
